# 실습하기

## 데이터 준비

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.neighbors import KNeighborsClassifier

df = pd.read_csv("https://raw.githubusercontent.com/YoungjinBD/dataset/main/iris.csv")
print(df.describe(include='all'))
print(df.info())

        sepal_length  sepal_width  petal_length  petal_width species
count     150.000000   150.000000    150.000000   150.000000     150
unique           NaN          NaN           NaN          NaN       3
top              NaN          NaN           NaN          NaN  setosa
freq             NaN          NaN           NaN          NaN      50
mean        5.843333     3.057333      3.758000     1.199333     NaN
std         0.828066     0.435866      1.765298     0.762238     NaN
min         4.300000     2.000000      1.000000     0.100000     NaN
25%         5.100000     2.800000      1.600000     0.300000     NaN
50%         5.800000     3.000000      4.350000     1.300000     NaN
75%         6.400000     3.300000      5.100000     1.800000     NaN
max         7.900000     4.400000      6.900000     2.500000     NaN
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        ------

## 데이터 전처리

### Min_Max 정규화

In [6]:
scaler = MinMaxScaler()
df['sepal_length'] = scaler.fit_transform(df[['sepal_length']])
df['sepal_width'] = scaler.fit_transform(df[['sepal_width']])
df['petal_length'] = scaler.fit_transform(df[['petal_length']])
df['petal_width'] = scaler.fit_transform(df[['petal_width']])

## 분석 데이터셋 준비

In [7]:
x = df[['sepal_length','sepal_width','petal_length','petal_width']]
y = df['species']

In [9]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=11)
print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

(120, 4) (30, 4) (120,) (30,)


## 분석 진행

In [11]:
knc = KNeighborsClassifier(n_neighbors=3)
knc.fit(x_train,y_train)
pred = knc.predict(x_test)

## 모델 평가

In [13]:
acc = accuracy_score(y_test,pred)
print(acc)
cm = confusion_matrix(y_test,pred)
print(cm)
cr = classification_report(y_test,pred)
print(cr)

0.9333333333333333
[[ 9  0  0]
 [ 0 10  0]
 [ 0  2  9]]
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00         9
  versicolor       0.83      1.00      0.91        10
   virginica       1.00      0.82      0.90        11

    accuracy                           0.93        30
   macro avg       0.94      0.94      0.94        30
weighted avg       0.94      0.93      0.93        30



# 연습하기

## iris

In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# 데이터 준비
df = pd.read_csv("https://raw.githubusercontent.com/YoungjinBD/dataset/main/iris.csv")
print(df.describe(include='all'))
print(df.info())

# 데이터 전처리
## 결측치 확인
print(df.isnull().sum())

## 데이터 정규화
scaler = MinMaxScaler()
df['sepal_length'] = scaler.fit_transform(df[['sepal_length']])
df['sepal_width'] = scaler.fit_transform(df[['sepal_width']])
df['petal_length'] = scaler.fit_transform(df[['petal_length']])
df['petal_width'] = scaler.fit_transform(df[['petal_width']])

# 분석 데이터 셋 준비
x = df[['sepal_length','sepal_width','petal_length','petal_width']]
y = df['species']

x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.2,random_state = 11)
print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

# 분석 진행
knc = KNeighborsClassifier(n_neighbors = 3)
knc.fit(x_train,y_train)
pred = knc.predict(x_test)

# 모델 평가
acc = accuracy_score(y_test,pred)
print(acc)
cm = confusion_matrix(y_test,pred)
print(cm)
cr = classification_report(y_test,pred)
print(cr)

        sepal_length  sepal_width  petal_length  petal_width species
count     150.000000   150.000000    150.000000   150.000000     150
unique           NaN          NaN           NaN          NaN       3
top              NaN          NaN           NaN          NaN  setosa
freq             NaN          NaN           NaN          NaN      50
mean        5.843333     3.057333      3.758000     1.199333     NaN
std         0.828066     0.435866      1.765298     0.762238     NaN
min         4.300000     2.000000      1.000000     0.100000     NaN
25%         5.100000     2.800000      1.600000     0.300000     NaN
50%         5.800000     3.000000      4.350000     1.300000     NaN
75%         6.400000     3.300000      5.100000     1.800000     NaN
max         7.900000     4.400000      6.900000     2.500000     NaN
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        ------

## titanic

In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.neighbors import KNeighborsClassifier

# 데이터 준비
df = pd.read_csv("https://raw.githubusercontent.com/YoungjinBD/dataset/main/titanic.csv")

# 데이터 전처리
## 결측치 확인
df['Age'].fillna(df['Age'].mean(),inplace=True)
df['Embarked'].fillna(df['Embarked'].mode()[0],inplace=True)

## 라벨인코딩
df['Sex'] = LabelEncoder().fit_transform(df['Sex'])
df['Embarked'] = LabelEncoder().fit_transform(df['Embarked'])

## 파생변수 생성
df['FamilySize'] = df['SibSp'] + df['Parch']

## 데이터 확인
print(df.describe(include='all'))

## 분석 데이터 셋 준비
x = df[['Pclass','Sex','Age','Fare','Embarked','FamilySize']]
y = df['Survived']

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2, random_state = 11)
print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

# 분석 진행
knc = KNeighborsClassifier(n_neighbors = 7)
knc.fit(x_train,y_train)
pred = knc.predict(x_test)

# 모델 평가
acc = accuracy_score(y_test,pred)
print(acc)
cm = confusion_matrix(y_test,pred)
print(cm)
cr = classification_report(y_test,pred)
print(cr)

        PassengerId    Survived      Pclass                     Name  \
count    891.000000  891.000000  891.000000                      891   
unique          NaN         NaN         NaN                      891   
top             NaN         NaN         NaN  Braund, Mr. Owen Harris   
freq            NaN         NaN         NaN                        1   
mean     446.000000    0.383838    2.308642                      NaN   
std      257.353842    0.486592    0.836071                      NaN   
min        1.000000    0.000000    1.000000                      NaN   
25%      223.500000    0.000000    2.000000                      NaN   
50%      446.000000    0.000000    3.000000                      NaN   
75%      668.500000    1.000000    3.000000                      NaN   
max      891.000000    1.000000    3.000000                      NaN   

               Sex         Age       SibSp       Parch  Ticket        Fare  \
count   891.000000  891.000000  891.000000  891.000000   

/tmp/ipykernel_62816/2862773128.py:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(),inplace=True)
/tmp/ipykernel_62816/2862773128.py:16: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', t