# 독립성 검정

In [18]:
import numpy as np
import pandas as pd
from scipy.stats import chi2_contingency
data_matrix = np.array([[50,75,125,175],[90,30,45,10]])
chi2,p,df,expected = chi2_contingency(data_matrix)

print('chi-square statistic : ',chi2)
print('p-value : ',p)
print('Degrees of freedom : ',df)
print('Expected frequencies table: ')
print(expected)

if p > 0.05:
    print('귀무가설을 기각할 수 없습니다. 두 변수는 독립적이며, 연관성이 없습니다.')
else:
    print('귀무가설을 기각합니다. 두 변수는 독립적이지 않으며, 연관성이 있습니다.')


chi-square statistic :  134.7511341579557
p-value :  5.117490956087995e-29
Degrees of freedom :  3
Expected frequencies table: 
[[ 99.16666667  74.375      120.41666667 131.04166667]
 [ 40.83333333  30.625       49.58333333  53.95833333]]
귀무가설을 기각합니다. 두 변수는 독립적이지 않으며, 연관성이 있습니다.


# 연습

In [19]:
import numpy as np
import pandas as pd
from scipy.stats import chi2_contingency
df = pd.read_csv("https://raw.githubusercontent.com/YoungjinBD/dataset/main/titanic.csv")
cross_table = pd.crosstab(df['Sex'],df['Survived'])
chi2,p,df,expected = chi2_contingency(cross_table)
print('chi-square statistic : ',chi2)
print('p-value : ',p)
print('Degrees of freedom : ',df)
print('Expected frequencies table: ')
print(expected)

if p > 0.05:
    print('귀무가설을 기각할 수 없습니다. 두 변수는 독립적이며, 연관성이 없습니다.')
else:
    print('귀무가설을 기각합니다. 두 변수는 독립적이지 않으며, 연관성이 있습니다.')


chi-square statistic :  260.71702016732104
p-value :  1.1973570627755645e-58
Degrees of freedom :  1
Expected frequencies table: 
[[193.47474747 120.52525253]
 [355.52525253 221.47474747]]
귀무가설을 기각합니다. 두 변수는 독립적이지 않으며, 연관성이 있습니다.


In [79]:
import pandas as pd
import numpy as np
from scipy.stats import chi2_contingency
df_titanic = pd.read_csv("https://raw.githubusercontent.com/YoungjinBD/dataset/main/titanic.csv")
print(df_titanic['Age'].isnull().sum())
df_titanic['Age'].fillna(df_titanic['Age'].mean(),inplace=True)
print(df_titanic['Age'].isnull().sum())
print(df_titanic['Age'].describe())
def grouping(row):
    if row < 20:
        answer = '10대'
    elif row <30:
        answer = '20대'
    elif row <40:
        answer = '30대'
    elif row <50:
        answer = '40대'
    elif row <60:
        answer = '50대'
    else:
        answer = '60대 이상'
    return answer
df_titanic['Age_group'] = df_titanic['Age'].apply(grouping)
cross_table = pd.crosstab(df_titanic['Age_group'],df_titanic['Survived'])
chi2,p,df,expect = chi2_contingency(cross_table)
print('chi-squared statistic : ',chi2)
print('p-value : ',p)
print('degrees of freedom : ',df)
print('기대값(Expected of frequenies table) : ')
print(expected)
if p > 0.05:
    print('귀무가설을 기각할 수 없습니다. 두 변수는 독립적이며, 연관성이 없습니다.')
else:
    print('귀무가설을 기각합니다. 두 변수는 연관성이 있습니다.')

177
0
count    891.000000
mean      29.699118
std       13.002015
min        0.420000
25%       22.000000
50%       29.699118
75%       35.000000
max       80.000000
Name: Age, dtype: float64
chi-squared statistic :  16.134525241016338
p-value :  0.006470311249228111
degrees of freedom :  5
기대값(Expected of frequenies table) : 
[[193.47474747 120.52525253]
 [355.52525253 221.47474747]]
귀무가설을 기각합니다. 두 변수는 연관성이 있습니다.


/tmp/ipykernel_93562/3421772722.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_titanic['Age'].fillna(df_titanic['Age'].mean(),inplace=True)


In [80]:
df_titanic.query('Age==40')

PassengerId  Survived  Pclass  \
30            31         0       1   
40            41         0       3   
161          162         1       2   
188          189         0       3   
209          210         1       1   
263          264         0       1   
319          320         1       1   
346          347         1       2   
360          361         0       3   
561          562         0       3   
609          610         1       1   
661          662         0       3   
670          671         1       2   

                                                  Name     Sex   Age  SibSp  \
30                            Uruchurtu, Don. Manuel E    male  40.0      0   
40      Ahlin, Mrs. Johan (Johanna Persdotter Larsson)  female  40.0      1   
161  Watt, Mrs. James (Elizabeth "Bessie" Inglis Mi...  female  40.0      0   
188                                   Bourke, Mr. John    male  40.0      1   
209                                   Blank, Mr. Henry    male  40.0      0   
263                              Harrison, Mr. William    male  40.0      0   
319  Spedden, Mrs. Frederic Oakley (Margaretta Corn...  female  40.0      1   
346                          Smith, Miss. Marion Elsie  female  40.0      0   
360                                 Skoog, Mr. Wilhelm    male  40.0      1   
561                                  Sivic, Mr. Husein    male  40.0      0   
609                          Shutes, Miss. Elizabeth W  female  40.0      0   
661                                  Badt, Mr. Mohamed    male  40.0      0   
670  Brown, Mrs. Thomas William Solomon (Elizabeth ...  female  40.0      1   

     Parch      Ticket      Fare Cabin Embarked Age_group  
30       0    PC 17601   27.7208   NaN        C       40대  
40       0        7546    9.4750   NaN        S       40대  
161      0  C.A. 33595   15.7500   NaN        S       40대  
188      1      364849   15.5000   NaN        Q       40대  
209      0      112277   31.0000   A31        C       40대  
263      0      112059    0.0000   B94        S       40대  
319      1       16966  134.5000   E34        C       40대  
346      0       31418   13.0000   NaN        S       40대  
360      4      347088   27.9000   NaN        S       40대  
561      0      349251    7.8958   NaN        S       40대  
609      0    PC 17582  153.4625  C125        S       40대  
661      0        2623    7.2250   NaN        C       40대  
670      1       29750   39.0000   NaN        S       40대